### ISSUE TITLE
无法更新provider

### ISSUE THREAD

**Issue by xianquu** [juzeon/fast-mail-bomber#54]
Getting providers from Shodan...
#0 /root/fast-mail-bomber/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /root/fast-mail-bomber/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /root/fast-mail-bomber/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /root/fast-mail-bomber/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()
#11 /root/fast-mail-bomber/libraries/providers/Shodan.php(7): GuzzleHttp\Client->get()
#12 /root/fast-mail-bomber/actions/update-providers.php(14): Shodan->get_providers()
#13 /root/fast-mail-bomber/index.php(13): require_once('...')
#14 {main}
Added 0 providers from Shodan.
Completed. Total added: 0

**Comment by tp1990** [comment]
same issue
